env:
  browser: true
  es2021: true
  "jest/globals": true
extends:
  - standard
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
  - jest
rules:
  prettier/prettier:
    - error
